From j8
ENV profile dev
EXPOSE 8080
#COPY ./target/demo-1.0.jar /app/demo-1.0.jar
#ADD ["/Users/hemantm/work/bigdata/demo/target/demo-1.0.jar", "/app/"]
VOLUME ["/app"]
WORKDIR /app
#RUN sh -c "echo pwd"
#RUN sh -c 'touch /app/target/demo-1.0.jar'
#ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/target/demo-1.0.jar"]

